[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExcelFiles = "89b67f3b-d1aa-5f6f-9ca4-282e8d98620d"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Inequality = "131cd6a8-f02b-4a66-8ce5-0a80ec47b73f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
MimiFAIRv2 = "db6a9ac4-572f-40b4-b774-4040310d200a"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
VegaDatasets = "0ae4a718-28b7-58ec-9efb-cded64d6d5b4"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"
